import { Gender } from "../models/gender.model.js";
import { LevelStudy } from "../models/levelStudy.model.js";
import { Locality } from "../models/locality.model.js";
import { Option } from "../models/option.model.js";
import { Question } from "../models/question.model.js";
import { GENDERS } from "../models/respondent.model.js";
import { Survey } from "../models/survey.model.js";

const questions = {
  "Te gusta la música": ["Si", "No", "Me es indiferente, pero la escucho"],
  "¿Consideras la música imprescindible en tu vida?": [
    "Si",
    "No",
    "En Ocasiones",
    "No la considero imprescindible, pero a veces la escucho",
  ],
  "Género musical favorito": [
    "Rock",
    "Pop",
    "Hip-hop",
    "Jazz",
    "Blues",
    "Reggae",
    "Country",
    "Metal",
    "Electronic",
    "Funk",
    "Salsa",
    "Tango",
    "Cumbia",
    "Reggaetón",
    "Flamenco",
    "Indie",
    "Punk",
    "Clásica",
    "Folk",
    "Rap",
    "Techno",
    "Dubstep",
  ],
  "Artista o grupo favorito": ["open"],
  "Canción favorita": ["open"],
  "¿Le das importancia a la letra o a la melodía de la canción?": [
    "Letra",
    "Melodía",
    "Ambos",
    "Depende de la canción",
  ],
  "¿Tus gustos musicales son cambiantes de acuerdo a los cambios emocionales internos?":
    ["Si", "No", "Si cambian, pero no se debe a mis emociones"],
  "¿Cuánto tiempo escuchas música durante el día?": [
    "Más de 2 horas",
    "Entre 1 y 2 horas",
    "Menos de 1 hora",
    "No escucho música",
    "o muy pocos minutos",
  ],
  "¿Cuál es tu momento favorito para escuchar música?": [
    "Mañana",
    "Tarde",
    "Noche",
  ],
  "¿Qué tipo de música prefieres para cada momento?": ["open"],
  "¿Hay algo más que te gustaría compartir sobre tus preferencias musicales?": [
    "open",
  ],
};

const locations = [
  { name: "AIBAL EL SILENCIO" },
  { name: "BAJO HONDO" },
  { name: "EL BREAL" },
  { name: "EL CAJON" },
  { name: "EL CAÑON" },
  { name: "EL CHURCAL" },
  { name: "EL COLETO" },
  { name: "EL QUEMADO" },
  { name: "EL REMANSO" },
  { name: "EL SIMBOLAR" },
  { name: "EL SOLITARIO" },
  { name: "FORTIN LA MADRID" },
  { name: "FORTIN PILCOMAYO NUEVO" },
  { name: "FORTIN SOLEDAD" },
  { name: "GUADALCAZAR" },
  { name: "LA ESPERANZA" },
  { name: "LA LAGUNA" },
  { name: "LA LIBERTAD" },
  { name: "LA REPRESA" },
  { name: "LA RINCONADA" },
  { name: "LAGUNA YEMA" },
  { name: "LAGUNITA" },
  { name: "LAS BANDERITAS" },
  { name: "LAS BOLIVIANAS" },
  { name: "LOS CHIRIGUANOS" },
  { name: "LOS POCITOS" },
  { name: "MATIAS GULACSI" },
  { name: "MEDIA LUNA" },
  { name: "PESCADO NEGRO" },
  { name: "POZO DE MAZA" },
  { name: "POZO DE MOLINA" },
  { name: "POZO DEL MORTERO" },
  { name: "PUERTO CABO IRIGOYEN" },
  { name: "RIO MUERTO" },
  { name: "SANTA ISABEL" },
  { name: "SOMBRERO NEGRO" },
  { name: "SUMAYEN" },
  { name: "VACA PERDIDA" },
  { name: "EL BAJO" },
  { name: "EL CHAÑARAL" },
  { name: "EL CHURCALITO" },
  { name: "EL LINDERO" },
  { name: "EL QUIMIL" },
  { name: "LAGUNA TRES PACES" },
  { name: "LAGUNA YACARE" },
  { name: "LOS CIENEGUITOS" },
  { name: "LA PALIZADA" },
  { name: "POZO RAMON" },
  { name: "SAN CAYETANO" },
  { name: "ALTO ALEGRE" },
  { name: "LA ZANJA" },
  { name: "POZO SARGENTO" },
  { name: "LA MOCHA" },
  { name: "TRES YUCHAN" },
  { name: "LA MADRUGADA" },
  { name: "BOCA DE PILAGAS" },
  { name: "COLONIA ITUZAINGO" },
  { name: "COLONIA PASTORIL" },
  { name: "COLONIA PRESIDENTE YRIGOYEN" },
  { name: "FORMOSA" },
  { name: "GRAN GUARDIA" },
  { name: "GUAYCOLEC" },
  { name: "ISLA 25 DE MAYO" },
  { name: "MOJON DE FIERRO" },
  { name: "SAN HILARIO" },
  { name: "BANCO LA EMILIA" },
  { name: "COLONIA DALMACIA" },
  { name: "MARIANO BOEDO" },
  { name: "PUENTE SAN HILARIO" },
  { name: "VILLA TRINIDAD" },
  { name: "BANCO PAYAGUA" },
  { name: "CABO ADRIANO AYALA" },
  { name: "COLONIA EL DORADO" },
  { name: "COLONIA EL NARANJITO" },
  { name: "COLONIA LAGUNA GOBERNADOR" },
  { name: "COLONIA SAN ANTONIO" },
  { name: "COLONIA SAN ISIDRO" },
  { name: "COLONIA YATAY" },
  { name: "EL ANGELITO" },
  { name: "EL MBIGUA" },
  { name: "ESTERITO" },
  { name: "GENERAL LUCIO V. MANSILLA" },
  { name: "HERRADURA" },
  { name: "LA PLAYA" },
  { name: "PASO POLENTA" },
  { name: "POSTA DEL SALADO" },
  { name: "POTRERO DE LOS CABALLOS" },
  { name: "RIACHO LINDO" },
  { name: "SAN FRANCISCO DE LAISHI" },
  { name: "TATANE" },
  { name: "TRES MOJONES" },
  { name: "VILLA ESCOLAR" },
  { name: "KILOMETRO 117" },
  { name: "BOLSA DEL PALOMO" },
  { name: "CAMPO BANDERA" },
  { name: "CAMPO GRANDE" },
  { name: "CAMPO LA CRUZ" },
  { name: "EL MISTOLAR" },
  { name: "EL TOTORAL" },
  { name: "INGENIERO GUILLERMO N. JUAREZ" },
  { name: "LA JUNTA" },
  { name: "POZO EL YACARE" },
  { name: "TENIENTE GENERAL ROSENDO M. FRAGA" },
  { name: "EL POTRERITO" },
  { name: "EL ROSILLO" },
  { name: "POZO DE LOS PATOS" },
  { name: "EL TREBOL" },
  { name: "TRES PALMITAS" },
  { name: "EL MILAGRO" },
  { name: "COMUNIDAD ABORIGEN WICHI FWINAFWAS" },
  { name: "A. FLORES" },
  { name: "CACIQUE COQUERO" },
  { name: "CAMPO ALEGRE" },
  { name: "CAMPO AZCURRA" },
  { name: "CAMPO DEL CIELO" },
  { name: "CHICO DOWAGAN" },
  { name: "COLONIA 14 DE MAYO" },
  { name: "COLONIA 20 DE JUNIO" },
  { name: "COLONIA ALTO ALEGRE" },
  { name: "COLONIA CEFERINO NAMUNCURA" },
  { name: "COLONIA EL ENSANCHE" },
  { name: "COLONIA EL PAVAO" },
  { name: "COLONIA EL SILENCIO" },
  { name: "COLONIA ISLA SOLA" },
  { name: "COLONIA JUAN BAUTISTA ALBERDI" },
  { name: "COLONIA JAVIER MUÑIZ" },
  { name: "COLONIA JUANITA" },
  { name: "COLONIA LA PREFERIDA" },
  { name: "COLONIA LAS CHOYAS" },
  { name: "COLONIA NAPENAY" },
  { name: "COLONIA SAN ANTONIO" },
  { name: "COLONIA SAN ISIDRO" },
  { name: "COLONIA SAN PABLO" },
  { name: "COLONIA SAN PEDRO" },
  { name: "COLONIA SAN ROQUE" },
  { name: "COLONIA SANTA ROSA" },
  { name: "COLONIA SARMIENTO" },
  { name: "COLONIA SIETE QUEBRACHOS" },
  { name: "COLONIA TATANE" },
  { name: "COLONIA UNION ESCUELA" },
  { name: "COMANDANTE FONTANA" },
  { name: "EL CACUY" },
  { name: "EL CEIBAL" },
  { name: "EL COGOIK" },
  { name: "EL CRUCE" },
  { name: "EL DESCANSO" },
  { name: "EL DIVISADERO" },
  { name: "EL MATADERO" },
  { name: "EL OCULTO" },
  { name: "EL PERDIDO" },
  { name: "EL RECREO" },
  { name: "EL SIMBOLAR" },
  { name: "EL TIMBO" },
  { name: "ESTANISLAO DEL CAMPO" },
  { name: "FORTIN CABO 1° LUGONES" },
  { name: "FORTIN SARGENTO 1° LEYES" },
  { name: "IBARRETA" },
  { name: "JUAN G. BAZAN" },
  { name: "KILOMETRO 15" },
  { name: "KILOMETRO 503" },
  { name: "LA CIERVA" },
  { name: "LA ESTRELLA" },
  { name: "LA INVERNADA" },
  { name: "LA LINEA" },
  { name: "LA MEDIA LUNA" },
  { name: "LA PAMPA" },
  { name: "LAGO VERDE" },
  { name: "LAS LOLAS" },
  { name: "LAS LOMITAS" },
  { name: "LAS MOCHAS" },
  { name: "LOMA SAN PABLO" },
  { name: "LOS TRES REYES" },
  { name: "LOTE 20 RURAL" },
  { name: "LOTE 27" },
  { name: "MAESTRA BLANCA GOMEZ" },
  { name: "PASO NAITE" },
  { name: "POSTA CAMBIO ZALAZAR" },
  { name: "POZO DEL TIGRE" },
  { name: "POZO HONDO" },
  { name: "POZO LARGO" },
  { name: "POZO NAVAGAN" },
  { name: "PUERTO LAVALLE" },
  { name: "PUNTA DE AGUA" },
  { name: "COLONIA OSVALDO QUIROGA" },
  { name: "RANERO CUE" },
  { name: "RIACHO DE ORO" },
  { name: "RINCON FLORIDO" },
  { name: "SAN CARLOS" },
  { name: "SAN CARLOS" },
  { name: "SAN MARTIN I" },
  { name: "SAN MARTIN II" },
  { name: "SAN SIMON" },
  { name: "SOLDADO D. SALVATIERRA" },
  { name: "SOLDADO I. SANCHEZ" },
  { name: "SUBTENIENTE PERIN" },
  { name: "TENIENTE BROWN" },
  { name: "TRES POZOS" },
  { name: "URBANA VIEJA" },
  { name: "VILLA GENERAL GÜEMES" },
  { name: "VILLA GENERAL MANUEL BELGRANO" },
  { name: "VILLA GENERAL URQUIZA" },
  { name: "BARTOLOME DE LAS CASAS" },
  { name: "CAMPO DE AVIACION" },
  { name: "COLONIA BARTOLOME DE LAS CASAS" },
  { name: "COLONIA DANTE SANDRELLI" },
  { name: "COLONIA EL CATORCE" },
  { name: "COLONIA ENSANCHE NORTE" },
  { name: "EL BELLACO" },
  { name: "LAQTASATANYIE" },
  { name: "LOS TRES REYES" },
  { name: "LOS JUBILADOS" },
  { name: "VILLA MARIN" },
  { name: "LA PANTALLA" },
  { name: "CAMPO TRES POZOS" },
  { name: "COLONIA LAKA-WICHI" },
  { name: "COLONIA ABORIGEN LA BOMBA" },
  { name: "LAGUNA ACEVAL" },
  { name: "LOTE 42" },
  { name: "LOTE 47" },
  { name: "COMUNIDAD LOTE 21" },
  { name: "APAYEREY" },
  { name: "BUENA VISTA" },
  { name: "COLONIA 25 DE MAYO" },
  { name: "COLONIA EL CEIBO" },
  { name: "COLONIA NUEVA" },
  { name: "COLONIA SANTA ROSA" },
  { name: "EL ESPINILLO" },
  { name: "EL POMBERO" },
  { name: "ISLA AZUL" },
  { name: "JULIO CUE" },
  { name: "LAGUNA GALLO" },
  { name: "LOMA ZAPATU" },
  { name: "LORO CUE" },
  { name: "MISION TACAAGLE" },
  { name: "PORTON NEGRO" },
  { name: "SALVACION" },
  { name: "SAN BLAS" },
  { name: "SAN CARLOS" },
  { name: "TRES LAGUNAS" },
  { name: "VILLA HERMOSA" },
  { name: "VILLA REAL" },
  { name: "VILLA RURAL" },
  { name: "VISTA ALEGRE" },
  { name: "PUESTO RAMONA" },
  { name: "COLONIA ABORIGEN" },
  { name: "LAGUNA TORO" },
  { name: "BUEY MUERTO" },
  { name: "CEIBO TRECE" },
  { name: "CLORINDA" },
  { name: "COLONIA LA PRIMAVERA" },
  { name: "COLONIA LOS SANTAFESINOS" },
  { name: "COLONIA SAN JUAN" },
  { name: "COLONIA SARMIENTO" },
  { name: "COLONIA SUDAMERICANA" },
  { name: "COSTA ALEGRE" },
  { name: "EL PARAISO" },
  { name: "EL RECODO" },
  { name: "ESPERANZA" },
  { name: "GARCETE CUE" },
  { name: "ISLA APANDO" },
  { name: "ISLA PUEN" },
  { name: "ISLA YOBAI GUAZU" },
  { name: "LA FRONTERA" },
  { name: "LAGUNA BLANCA" },
  { name: "LAGUNA NAICK-NECK" },
  { name: "LOMA HERMOSA" },
  { name: "LOMA TUYUTU" },
  { name: "LUCERO CUE" },
  { name: "MARCA M" },
  { name: "MARTIN FIERRO" },
  { name: "PALMA SOLA" },
  { name: "PRESIDENTE AVELLANEDA" },
  { name: "PUERTO PILCOMAYO" },
  { name: "PUNTA GUIA" },
  { name: "RIACHO HE-HE" },
  { name: "SIETE PALMAS" },
  { name: "SOL DE MAYO" },
  { name: "SOL DE MAYO" },
  { name: "TORO PASO" },
  { name: "JOSE MARIA PAZ" },
  { name: "PASO ANGELITO" },
  { name: "RODEO TAPITI" },
  { name: "RIACHO NEGRO" },
  { name: "9 DE JULIO" },
  { name: "BAÑADERO" },
  { name: "CABO 1° NOROÑA" },
  { name: "CAMPO HARDY" },
  { name: "CAMPO SAN RAFAEL" },
  { name: "PIRANE" },
  { name: "COLONIA 5 DE OCTUBRE" },
  { name: "COLONIA CAMPO VILLAFAÑE" },
  { name: "COLONIA CAMPO VILLAFAÑE" },
  { name: "COLONIA EL ALBA" },
  { name: "COLONIA EL CHAJA" },
  { name: "COLONIA EL COMIENZO" },
  { name: "COLONIA EL DESAGUADERO" },
  { name: "COLONIA EL OLVIDO" },
  { name: "COLONIA EL PALMAR" },
  { name: "COLONIA EL PROGRESO" },
  { name: "COLONIA EL RINCON" },
  { name: "COLONIA EL ZAPALLITO" },
  { name: "COLONIA ESPERANZA" },
  { name: "COLONIA ITATI" },
  { name: "COLONIA LA DISCIPLINA" },
  { name: "COLONIA LA UNION" },
  { name: "COLONIA LOMA SENES" },
  { name: "COLONIA PAMPA VILLANUEVA" },
  { name: "COLONIA RIGONATO" },
  { name: "COLONIA RODA" },
  { name: "COLONIA SANTA CRUZ" },
  { name: "COLONIA WEITZEL" },
  { name: "COPO BLANCO" },
  { name: "COSTA RIACHO ALAZAN" },
  { name: "EL ALBA" },
  { name: "EL BOSQUECILLO" },
  { name: "EL COATI" },
  { name: "EL COLORADO" },
  { name: "EL CORRALITO" },
  { name: "EL GATO" },
  { name: "EL GUAJO" },
  { name: "EL IBAGAY" },
  { name: "EL PIQUETE" },
  { name: "EL POI" },
  { name: "EL RESGUARDO" },
  { name: "EL SALADILLO" },
  { name: "EL SALADO" },
  { name: "ESTERO PATIÑO" },
  { name: "KILOMETRO 142" },
  { name: "KILOMETRO 210" },
  { name: "KILOMETRO 224" },
  { name: "LA ESPERANZA" },
  { name: "LA FLORESTA" },
  { name: "LA LOMA" },
  { name: "LA PICADITA" },
  { name: "LA SIRENA" },
  { name: "LAS CAÑITAS" },
  { name: "LOMA DEL QUEBRANTO" },
  { name: "LOS MATACOS" },
  { name: "LOTE 108 LADRILLERIA" },
  { name: "LOTE 11" },
  { name: "LOTE 17-LEGUA A" },
  { name: "MERCEDES CUE" },
  { name: "MONTE LINDO" },
  { name: "MONTE QUEMADO" },
  { name: "MURUA" },
  { name: "PALO SANTO" },
  { name: "PARATODOS" },
  { name: "PILAGAS III" },
  { name: "PIRANE" },
  { name: "POTRERO NORTE" },
  { name: "POTRERO ÑANDU" },
  { name: "RACEDO ESCOBAR" },
  { name: "RODAS" },
  { name: "VILLA KILOMETRO 213" },
  { name: "LOMA SENES" },
  { name: "SOLDADO EDMUNDO SOSA" },
  { name: "LOTE 219" },
  { name: "CENTRO FORESTAL PIRANE" },
  { name: "LA LOMITA" },
  { name: "LOMA SENES SUR" },
  { name: "LOTE 31 MAYOR VILLAFAÑE" },
  { name: "LOMA ALBERDI" },
  { name: "CAMPO DEL ACHA" },
  { name: "EL ALAMBRADO" },
  { name: "EL ALGARROBO" },
  { name: "EL CHIVIL" },
  { name: "EL DIVISADERO" },
  { name: "EL PALMARCITO" },
  { name: "EL POTRILLO" },
  { name: "EL ROSARIO" },
  { name: "EL SILENCIO" },
  { name: "EL TABIQUE" },
  { name: "EL TUCUMANCITO" },
  { name: "LA BREA" },
  { name: "LA MOCHA" },
  { name: "LOTE 1" },
  { name: "LOTE 8" },
  { name: "MARIA CRISTINA" },
  { name: "MISION SAN ANDRES" },
  { name: "PALMAR LARGO" },
  { name: "PALO SECO" },
  { name: "POZO CERCADO" },
  { name: "SAN MARTIN" },
  { name: "SANTA ROSA" },
  { name: "SANTA TERESA" },
  { name: "TRES PALMAS" },
  { name: "TRES POZOS" },
  { name: "BARRIO EL FAVORITO" },
  { name: "EL BREAL" },
  { name: "EL CHORRO" },
  { name: "EL CRUCE" },
  { name: "EL ESTANQUE" },
  { name: "EL QUEBRACHO" },
  { name: "EL TRONQUITO" },
  { name: "LA PAMPA" },
  { name: "LAS CAÑITAS" },
  { name: "POZO LA CHIVA" },
  { name: "SAN MIGUEL" },
  { name: "COMUNIDAD 7 DE JUNIO" },
  { name: "VILLA DEVOTO" },
  { name: "POZO DEL OSO" },
  { name: "EL SOL" },
  { name: "POZO CHARATA" },
  { name: "POZO CABALLO" },
  { name: "LA BATERIA" },
  { name: "COMUNIDAD ABORIGEN WICHI" },
  { name: "LAS PALMITAS" },
  { name: "COMUNIDAD WICHI OBLITAJ" },
  { name: "PUERTO IRIGOYEN" },
  { name: "COMUNIDAD WICHI BARRIO EL COLORADO" },
  { name: "EL SAUZALITO" },
  { name: "POSTA ZALAZAR " },
  { name: "LAS CAÑITAS" },
  { name: "COL. SAN JOSE" },
];

const levelStudies = [
  { name: "Primario" },
  { name: "Secundario" },
  { name: "Terciario" },
  { name: "Terciario Incompleto" },
  { name: "Universitario" },
  { name: "Universitario Incompleto" },
];

const genders = [
  { name: GENDERS.FENEMINO },
  { name: GENDERS.MASCULINO },
  { name: GENDERS.NO_BINARIO },
  { name: GENDERS.OTRO },
];

export const createDefaultValues = async () => {
  const genderCount = await Gender.count();
  if (genderCount == 0) {
    const survey = await Survey.findOrCreate({
      where: { title: "Gustos Musicales" },
      defaults: {
        description: "",
        status: true,
      },
    });

    const qs = Object.keys(questions);

    qs.forEach(async (q) => {
      const [question] = await Question.findOrCreate({
        where: { question: q, surveyId: survey[0].id },
      });

      const ops = questions[question.question];

      ops.forEach(async (op) => {
        const [option] = await Option.findOrCreate({
          where: {
            option: op,
            questionId: question.id,
          },
        });
      });
    });

    await Gender.bulkCreate(genders);
    await Locality.bulkCreate(locations);
    await LevelStudy.bulkCreate(levelStudies);
  }
};
